import type { RepoData } from "../src/types";

export const makeRepoData = (overrides: Partial<RepoData> = {}): RepoData => ({
	owner: "test-owner",
	repo: "test-repo",
	isArchived: false,
	pushedAt: new Date().toISOString(),
	createdAt: "2020-01-01T00:00:00Z",
	hasIssues: true,
	defaultBranch: "main",
	licenseKey: "mit",
	licenseName: "MIT License",
	licenseUrl: "https://opensource.org/licenses/MIT",
	isSecurityPolicyEnabled: false,
	securityPolicyContent: null,
	hasVulnerabilityAlertsEnabled: true,
	branchProtectionRules: [],
	recentCommits: [],
	releases: [],
	workflowFiles: [],
	hasDependabot: false,
	hasRenovate: false,
	treeFiles: [],
	vulnerabilityAlerts: [],
	ciiBadgeLevel: null,
	webhooks: [],
	issueActivityCount: 0,
	spdxId: null,
	...overrides,
});
